services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
  
  psql:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/psql/data:/data
      - ./docker-data/psql/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  discord:
    depends_on:
      - redis
      - psql
    build:
      dockerfile: KumaKaiNi.Client.Discord/Dockerfile
      context: ./src
    env_file: .env
  
  telegram:
    depends_on:
      - redis
      - psql
    build:
      dockerfile: KumaKaiNi.Client.Telegram/Dockerfile
      context: ./src
    env_file: .env
  
  request-processor:
    depends_on:
      - redis
      - psql
    build:
      dockerfile: KumaKaiNi.RequestProcessor/Dockerfile
      context: ./src
    env_file: .env