name: Build and Push Docker Image

on:
  workflow_call: 
    inputs:
      build_version:
        required: true
        type: string
      dotnet_project_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      docker_registry:
        required: true
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v2.2.1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.docker_registry }}
          username: ${{ secrets.docker_registry_username }}
          password: ${{ secrets.docker_registry_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ${{ secrets.docker_registry }}/${{ inputs.image_name }}
          tags: type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: src/
          file: |
            src/${{ inputs.dotnet_project_name }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            - BUILD_VERSION=${{ inputs.build_version }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max